backend:
  name: git-gateway
  branch: master

media_folder: static/images
public_folder: /images
locale: 'pt'

collections:
  - name: 'feminino'
    label: 'Roupas Femininas'
    folder: 'src/pages/produtos'
    filter: {field: "category", value: "feminino"}
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Nome', name: 'title', widget: 'string' }
      - { label: 'Código', name: 'code', widget: 'string' }
      - { label: 'Imagem principal', name: 'image', widget: 'image', allow_multiple: false }
      - { label: 'Demais imagens', name: 'images', widget: 'image', allow_multiple: true }
      - label: "Categoria"
        name: "category"
        widget: "select"
        multiple: false
        options:
          - { label: "Feminino", value: "feminino" }
          - { label: "Masculino", value: "masculino" }
          - { label: "Infantil", value: "infantil" }
          - { label: "Esportivo", value: "esportivo" }
          - { label: "Moda íntima", value: "moda-intima" }
          - { label: "Plus size", value: "plus-size" }
      - { label: 'Em detaque?', name: 'featured', widget: 'boolean', default: false }
