backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
media_folder: static/images
public_folder: /images
locale: 'pt'

collections:
  - name: 'feminino'
    label: 'Roupas Femininas'
    label_singular: 'roupa feminina'
    folder: 'src/pages/produtos'
    filter: { field: 'category', value: 'feminino' }
    create: true
    editor:
      preview: false
    fields:
      - {
          label: 'Categoria',
          name: 'category',
          widget: 'hidden',
          default: 'feminino',
        }
      - { label: 'Nome', name: 'title', widget: 'string' }
      - { label: 'Código', name: 'code', widget: 'string' }
      - {
          label: 'Imagem principal',
          name: 'image',
          widget: 'image',
          allow_multiple: false,
        }
      - {
          label: 'Demais imagens',
          name: 'images',
          widget: 'image',
          allow_multiple: true,
          required: false,
        }
      - {
          label: 'Data de inclusão',
          name: 'date',
          widget: 'date',
          dateFormat: 'DD/MM/YYYY',
          format: 'YYYY-MM-DD',
        }
  - name: 'masculino'
    label: 'Roupas Masculinas'
    label_singular: 'roupa masculina'
    folder: 'src/pages/produtos'
    filter: { field: 'category', value: 'masculino' }
    create: true
    editor:
      preview: false
    fields:
      - {
          label: 'Categoria',
          name: 'category',
          widget: 'hidden',
          default: 'masculino',
        }
      - { label: 'Nome', name: 'title', widget: 'string' }
      - { label: 'Código', name: 'code', widget: 'string' }
      - {
          label: 'Imagem principal',
          name: 'image',
          widget: 'image',
          allow_multiple: false,
        }
      - {
          label: 'Demais imagens',
          name: 'images',
          widget: 'image',
          allow_multiple: true,
          required: false,
        }
      - {
          label: 'Data de inclusão',
          name: 'date',
          widget: 'date',
          dateFormat: 'DD/MM/YYYY',
          format: 'YYYY-MM-DD',
        }
  - name: 'infantil'
    label: 'Roupas Infantis'
    label_singular: 'roupa infantil'
    folder: 'src/pages/produtos'
    filter: { field: 'category', value: 'infantil' }
    create: true
    editor:
      preview: false
    fields:
      - {
          label: 'Categoria',
          name: 'category',
          widget: 'hidden',
          default: 'infantil',
        }
      - { label: 'Nome', name: 'title', widget: 'string' }
      - { label: 'Código', name: 'code', widget: 'string' }
      - {
          label: 'Imagem principal',
          name: 'image',
          widget: 'image',
          allow_multiple: false,
        }
      - {
          label: 'Demais imagens',
          name: 'images',
          widget: 'image',
          allow_multiple: true,
          required: false,
        }
      - {
          label: 'Data de inclusão',
          name: 'date',
          widget: 'date',
          dateFormat: 'DD/MM/YYYY',
          format: 'YYYY-MM-DD',
        }
  - name: 'esportivo'
    label: 'Roupas Esportivas'
    label_singular: 'roupa esportiva'
    folder: 'src/pages/produtos'
    filter: { field: 'category', value: 'esportivo' }
    create: true
    editor:
      preview: false
    fields:
      - {
          label: 'Categoria',
          name: 'category',
          widget: 'hidden',
          default: 'esportivo',
        }
      - { label: 'Nome', name: 'title', widget: 'string' }
      - { label: 'Código', name: 'code', widget: 'string' }
      - {
          label: 'Imagem principal',
          name: 'image',
          widget: 'image',
          allow_multiple: false,
        }
      - {
          label: 'Demais imagens',
          name: 'images',
          widget: 'image',
          allow_multiple: true,
          required: false,
        }
      - {
          label: 'Data de inclusão',
          name: 'date',
          widget: 'date',
          dateFormat: 'DD/MM/YYYY',
          format: 'YYYY-MM-DD',
        }
  - name: 'moda-intima'
    label: 'Moda Íntima'
    label_singular: 'moda íntima'
    folder: 'src/pages/produtos'
    filter: { field: 'category', value: 'moda-intima' }
    create: true
    editor:
      preview: false
    fields:
      - {
          label: 'Categoria',
          name: 'category',
          widget: 'hidden',
          default: 'moda-intima',
        }
      - { label: 'Nome', name: 'title', widget: 'string' }
      - { label: 'Código', name: 'code', widget: 'string' }
      - {
          label: 'Imagem principal',
          name: 'image',
          widget: 'image',
          allow_multiple: false,
        }
      - {
          label: 'Demais imagens',
          name: 'images',
          widget: 'image',
          allow_multiple: true,
          required: false,
        }
      - {
          label: 'Data de inclusão',
          name: 'date',
          widget: 'date',
          dateFormat: 'DD/MM/YYYY',
          format: 'YYYY-MM-DD',
        }
  - name: 'plus-size'
    label: 'Roupas Plus Size'
    label_singular: 'roupa plus size'
    folder: 'src/pages/produtos'
    filter: { field: 'category', value: 'moda-intima' }
    create: true
    editor:
      preview: false
    fields:
      - {
          label: 'Categoria',
          name: 'category',
          widget: 'hidden',
          default: 'plus-size',
        }
      - { label: 'Nome', name: 'title', widget: 'string' }
      - { label: 'Código', name: 'code', widget: 'string' }
      - {
          label: 'Imagem principal',
          name: 'image',
          widget: 'image',
          allow_multiple: false,
        }
      - {
          label: 'Demais imagens',
          name: 'images',
          widget: 'image',
          allow_multiple: true,
          required: false,
        }
      - {
          label: 'Data de inclusão',
          name: 'date',
          widget: 'date',
          dateFormat: 'DD/MM/YYYY',
          format: 'YYYY-MM-DD',
        }
